apiVersion: apps/v1                                           
kind: Deployment                                              
metadata:
  name: ksj-web                                              
  labels:
    app: ksj-web                                              
spec:
  replicas: 1                                           
                                                            
  selector:                                              
    matchLabels:
      app: ksj-web
  template:                                            
    metadata:
      labels:
        app: ksj-web                                               
    spec:
      containers:
      - name: apache                                            
        image: 049474991519.dkr.ecr.ap-northeast-2.amazonaws.com/ksj-ecr-repo:apache2                                               
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      - name: tomcat
        image: 049474991519.dkr.ecr.ap-northeast-2.amazonaws.com/ksj-ecr-repo:tomcat
        imagePullPolicy: Always
        ports:
        - containerPort: 8009
