apiVersion: v1
kind: Service
metadata:
        name: web-service
spec:
        type: LoadBalancer
        selector:
                app: ksj-web
        ports:
                - protocol: TCP
                  port: 80
                  targetPort: 80 
